"""added subclasses and attack_defense columns

Revision ID: 02bf58bd1bc6
Revises: 2bf1377548a4
Create Date: 2023-06-14 22:04:50.602845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bf58bd1bc6'
down_revision = '2bf1377548a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subclasses', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('attack_defense', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('attack_defense')
        batch_op.drop_column('subclasses')

    # ### end Alembic commands ###
