"""Initial migration

Revision ID: 2bf1377548a4
Revises: 
Create Date: 2023-06-14 21:06:41.696709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf1377548a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('editions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('element', sa.String(), nullable=True),
    sa.Column('rune_type', sa.String(), nullable=True),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    op.drop_table('sets')
    # ### end Alembic commands ###
