"""update tables

Revision ID: ca6cffdddc2a
Revises: 02bf58bd1bc6
Create Date: 2023-06-17 21:21:21.934907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6cffdddc2a'
down_revision = '02bf58bd1bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subclass1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subclass2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('effect')
        batch_op.drop_column('subclasses')
        batch_op.drop_column('artist')

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.drop_column('editions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editions', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('subclasses', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('effect', sa.TEXT(), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('subclass2')
        batch_op.drop_column('subclass1')

    # ### end Alembic commands ###
