"""add rarity column

Revision ID: fddd2199fe8c
Revises: ca6cffdddc2a
Create Date: 2023-06-17 21:51:21.468950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddd2199fe8c'
down_revision = 'ca6cffdddc2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rarity', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('rarity')

    # ### end Alembic commands ###
